# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x1a\x1fgoogle/protobuf/timestamp.proto\" \n\rClientRequest\x12\x0f\n\x07Request\x18\x01 \x01(\t\"A\n\x0e\x43lientResponse\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\"V\n\x0bVoteRequest\x12\x0e\n\x06NodeID\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x05\x12\x14\n\x0cLastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bLastLogTerm\x18\x04 \x01(\x05\"L\n\x0cVoteResponse\x12\x0e\n\x06NodeID\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x05\x12\x0c\n\x04Vote\x18\x03 \x01(\x08\x12\x10\n\x08LeaseEnd\x18\x04 \x01(\x05\")\n\x08LogEntry\x12\x0c\n\x04Term\x18\x01 \x01(\x05\x12\x0f\n\x07\x43ommand\x18\x02 \x01(\t\"\x9d\x01\n\nLogRequest\x12\x10\n\x08LeaderID\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x05\x12\x14\n\x0cPrefixLength\x18\x03 \x01(\x05\x12\x12\n\nPrefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0c\x43ommitLength\x18\x05 \x01(\x05\x12\x1d\n\nLogEntries\x18\x06 \x03(\x0b\x32\t.LogEntry\x12\x10\n\x08LeaseEnd\x18\x07 \x01(\x05\"J\n\x0bLogResponse\x12\x0e\n\x06NodeID\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x05\x12\x0b\n\x03\x41\x63k\x18\x03 \x01(\x05\x12\x10\n\x08Response\x18\x04 \x01(\x08\x32\x9f\x01\n\x08RaftNode\x12\x30\n\x0bServeClient\x12\x0e.ClientRequest\x1a\x0f.ClientResponse\"\x00\x12\x31\n\x10ServeVoteRequest\x12\x0c.VoteRequest\x1a\r.VoteResponse\"\x00\x12.\n\x0fServeLogRequest\x12\x0b.LogRequest\x1a\x0c.LogResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTREQUEST']._serialized_start=47
  _globals['_CLIENTREQUEST']._serialized_end=79
  _globals['_CLIENTRESPONSE']._serialized_start=81
  _globals['_CLIENTRESPONSE']._serialized_end=146
  _globals['_VOTEREQUEST']._serialized_start=148
  _globals['_VOTEREQUEST']._serialized_end=234
  _globals['_VOTERESPONSE']._serialized_start=236
  _globals['_VOTERESPONSE']._serialized_end=312
  _globals['_LOGENTRY']._serialized_start=314
  _globals['_LOGENTRY']._serialized_end=355
  _globals['_LOGREQUEST']._serialized_start=358
  _globals['_LOGREQUEST']._serialized_end=515
  _globals['_LOGRESPONSE']._serialized_start=517
  _globals['_LOGRESPONSE']._serialized_end=591
  _globals['_RAFTNODE']._serialized_start=594
  _globals['_RAFTNODE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
